services:
  web:
    build: .
    container_name: science_docs_app
    ports:
      - "8000:8000"
    volumes:
      # Пробрасываем папку bin внутрь контейнера, чтобы БД sqlite
      # и скачанные отчеты не пропадали при пересоздании контейнера.
      - /opt/sdvolume/bin:/app/bin
      - /opt/sdvolume/csv_files:/app/csv_files
    env_file:
      - /opt/sdvolume/info.env
    restart: unless-stopped
